### PR TITLE
Big Mic Mac

### LINKED ISSUE #2: Introducing Ordinal Invariants
We use the notions of ordinal invariants, but we should be introducing them.

### LINKED ISSUE #3: Typos
p1: and was successfully->which has been successfully
p3: on can
p4: relation prove
p5: we can be a bit more precise for the definition of antichain branch: \forall w\in B, \exists v such that wv\in L\setminus B
p5: the word a -> the word a^k
p6: consider w to be a maximal element
p6: to be defined: max order type, height, width
p7: yield o -> yield
p10: maybe a non-example of Cor 17, where the downet of a chain is not wqo

### LINKED ISSUE #4: Chains vs Grids
Either remove `chains` from the formulations or introduce `grids` for the infix relation as products of chains. Theorems using `chains` and `infix` are just wrong.

### PR DESCRIPTION
**Pull request by AliaumeL**
- [x] Splitting between *bounded languages* (theoretical) and *amalgamation systems* (decision procedures)
- [x] Refining intro to sound more pretentious
- [x] Removing regular languages specific proofs
- [x] Defining ordinal invariants and computing them 
- [x] Removing the mention of "grids"
- [x] Finalize the "effective part" with uniform notations and conventions
- [x] Adding lexicographic orders to the conclusion

### CODE REVIEW

**Comment by AliaumeL** [comment]
@strangeglyph I have a problem with the notion of `rational transduction`. 

From what I understand, these are computed by non-deterministic automata with outputs in $\Gamma^*$, which is for instance the case in <https://hal.science/hal-01308509/document> (first paper that comes to mind). In particular, for any such transduction $f$, there exist fixed constants $(a, b) \in \mathbb{N}$ such that $\max \set{ |v| \mid v \in f(u) } \leq a |u| + b$ for all $u \in \Sigma^*$. 

For this reason, the relation $\Sigma^* \times \set{a,b}^*$ cannot be expressed using a `rational transduction`. Which seems to be a problem for your proof and already appears in [Section 4.1, <https://arxiv.org/pdf/2405.10296>]. 

This can be solved by allowing epsilon transitions in the computational model, and some papers seem to assume that. 

1. I am missing something?
2. Could we lower the requirements to go below and ask only for "regular relations" (i.e., synchronous)?

**Review by strangeglyph — COMMENTED** [review]
Looks good! I especially like the rewritten introduction

**Comment by strangeglyph** [comment]
> @strangeglyph I have a problem with the notion of `rational transduction`.
> 
> From what I understand, these are computed by non-deterministic automata with outputs in $\Gamma^_$, which is for instance the case in https://hal.science/hal-01308509/document (first paper that comes to mind). In particular, for any such transduction $f$, there exist fixed constants $(a, b) \in \mathbb{N}$ such that $\max \set{ |v| \mid v \in f(u) } \leq a |u| + b$ for all $u \in \Sigma^_$.
> 
> For this reason, the relation Σ ∗ × { a , b } ∗ cannot be expressed using a `rational transduction`. Which seems to be a problem for your proof and already appears in [Section 4.1, https://arxiv.org/pdf/2405.10296].
> 
> This can be solved by allowing epsilon transitions in the computational model, and some papers seem to assume that.
> 
>     1. I am missing something?
> 
>     2. Could we lower the requirements to go below and ask only for "regular relations" (i.e., synchronous)?

My go-to reference is Berstel's book on transductions: https://www-igm.univ-mlv.fr/~berstel/LivreTransductions/LivreTransductions.pdf

Quoting from Chapter 5, page 64

> 5.2 The rational constants τK : A* → B* defined for a fixed regular language K ⊂ B* by τK (x) = K are rational. 

It's true that following the definition in your linked paper, this would only work for finite languages. I'll try and see if I can untangle this.

**Comment by strangeglyph** [comment]
I do think this is just an unfortunate choice of terminology of the paper you picked out. They seem to be considering rational *functions*, not *relations*, but usually transducers are assumed to produce relations.

One other argument in favor of Berstel's definition: A well-known statement is that rational transductions are expressible (in fact, identical to) composition of homomorphism, inverse homomorphism and intersection with regular languages. Clearly, inverse homomorphisms may have an arbitrarily large images. In particular, take the homomorphism

    f_Σ : a ↦ ε for a in Σ

Then for an arbitrary language L over Σ, the transduction f_{a,b}^-1 ∘ f_Σ is the transduction that we want.

**Comment by AliaumeL** [comment]
Ok, thanks a lot for looking into it!
It is true that I am more familiar with the functional setting, hence my surprise ^^.

I revert to your proofs as soon as possible, and will add the precise link to what you pointed at + your example (for the unknowledgeable readers like me).

**Comment by NathanLhote** [comment]
I agree with @strangeglyph ! the canonical notion of rational relations is the one from Berstel,it is what you get if you consider rational(regular) expressions over the product of two free monoids: A * x B *

**Comment by AliaumeL** [comment]
@strangeglyph @NathanLhote 

I merged the pull request, but there are still some to-dos inside it.
I think it is now time to polish the drawings and overall "local readability" of the paper.

**Pull request merged**
